### ISSUE TITLE
how to compile ?

### ISSUE THREAD

**Issue by tissatussa** [Oscar-Gavira/Coiled#2]
i see no Makefile ..
and can Coiled be compiled on Linux ?
and / or can you provide Linux releases ?

**Comment by Oscar-Gavira** [comment]
Hello tissatussa.

I don't know how Makefiles work, I suppose they are more used at the Linux level.
Coiled for Linux cannot currently be compiled. But I will keep it in mind for the next versions. I will investigate.

To compile the projects you need GUI codeblocks. https://www.codeblocks.org/
Each project contains a .cbp file that is the project container to be edited / compiled using codeblocks.
You can use any other editor, just like you can use another compiler. I use Mingw. 

******************************************************************************************************************

Hola tissatussa.

No se como funciona los archivos Makefile, supongo que son más usados a nivel de Linux.
Actualmente no se puede compilar Coiled para Linux. Pero lo tendré en cuenta para las siguientes versiones. Investigare.

Para compilar los proyectos necesitas GUI codeblocks. https://www.codeblocks.org/
Cada proyecto contiene un archivo .cbp que es el contenedor del proyecto para ser editados/compilados mediante codeblocks.
Puedes usar cualquier otro editor, al igual que puedes usar otro compilador. Yo utilizo Mingw.

**Comment by tissatussa** [comment]
Thanks !  I managed to compile Coiled v1.1 on Linux by your makefile !
First, i did
`make help`
and so i choose the second option  `make LinuxX64=true X64`  which gave me a proper 64-bit Linux binary.
However, your method is not common : just  `make`  should do, your script can detect the OS and CPU architecture !?

**Comment by tissatussa** [comment]
Btw. during (linux) compile a bunch of  .so  files were created .. are (some of) those needed when running Coiled ?  Without them Coiled seems to play OK ..

**Comment by Oscar-Gavira** [comment]
> 
> 
> Thanks ! I managed to compile Coiled v1.1 on Linux by your makefile ! First, i did `make help` and so i choose the second option `make LinuxX64=true X64` which gave me a proper 64-bit Linux binary. However, your method is not common : just `make` should do, your script can detect the OS and CPU architecture !?

Hello tissatussa
I am learning how to generate makefile through tutorials on the internet and from other makefiles.
I guess it's not common, but it works for now. Little by little I will improve the makefile file.
By the way it is not official yet version 1.1 has errors. It will be there shortly. 

----------------------------------------------------------------------------------------------------

Hola tissatussa
Estoy aprendiendo a generar makefile mediante tutoriales en internet y de otros makefile.
Supongo que no es común, pero funciona de momento. Poco a poco iré mejorando el archivo makefile.
Por cierto no es oficial todavía la versión 1.1 tiene errores. Dentro de poco estará.

**Comment by Oscar-Gavira** [comment]
> 
> 
> Btw. during (linux) compile a bunch of .so files were created .. are (some of) those needed when running Coiled ? Without them Coiled seems to play OK ..

The .so files are necessary for managing the Syzygy, Gaviota and BitBases end tables and the NNUE neural network.
If you delete the .so files Coiled works in basic mode, with internal ELO 2600 evaluation and no end tables or nnue.
If you open Coiled in finish mode it warns you that it has not been able to load these .so files and it cannot use end or nnue tables. 

--------------------------------------------------------------------------------------------------------------------------------------------

Los archivos .so son necesarios para el manejo de las tablas de finales Syzygy, Gaviota y BitBases y la red neuronal NNUE.
Si borra los archivos .so Coiled funciona en modo básico, con la evaluación interna ELO 2600 y sin tablas de finales ni nnue.
Si abre Coiled en modo terminar te advierte de que no a podido cargar dichos archivos .so y no puede hacer uso de tablas de finales o de nnue.
