### ISSUE TITLE
Illegal moves

### ISSUE THREAD

**Issue by AlexBrunetti** [Oscar-Gavira/Coiled#3]
[cuteswiss_session_bad.zip](https://github.com/Oscar-Gavira/Coiled/files/7330349/cuteswiss_session_bad.zip)

**Comment by Oscar-Gavira** [comment]
Gracias AlexBrunetti

Fuente del error: http://talkchess.com/forum3/viewtopic.php?f=2&t=78401

- Fallo en buffer en partidas largas de 180 jugadas en adelante. Realizando movimientos ilegales. Eliminación setbuf(stdout, NULL); setbuf(stdin, NULL); hPly = 0 ...
- Modificado el método SplitString.
- Test 960 partidas. 0 jugadas ilegales. [Test_error.zip](https://github.com/Oscar-Gavira/Coiled/files/7344846/Test_error.zip)

Solucionado, en la proxima versión 1.1.
